// <auto-generated />
namespace VentasAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class PrimerVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrimerVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "202109190036589_PrimerVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
